# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: Ethereum Dashboards
description: A collection of useful dashboards for the Ethereum ecosystem.
keywords: ethereum, dashboard, eth, analytics, metrics
url: https://ethereumdashboards.com
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
port: 4400
livereload: true

# Plugins
plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false


# Assets
bootstrap_js: <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
bootstrap_css: <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


# Announcement
announcement:
  enabled: true
  theme: default # default, ethereum, etherealize, telegram, purple, red
  # img: /assets/img/announcements/etherealize.png # optional, leave blank for megaphone
  text: "Announcing: The Bull Case for ETH"
  link: https://ethdigitaloil.com
  cta: Read ↗
